# Generated by Django 4.2.2 on 2023-06-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_snack_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(default='none'),
        ),
    ]
